// Auto-generated by scripts/build.py - do not edit manually
const files = [
  "chicken-with-fennel-beans-lemon.md",
  "fasolakia.md",
  "insalata-pantesca.md",
  "lentejas-a-la-margarita.md",
  "moussaka.md",
  "tuna-and-white-bean-salad.md"
];
