// Auto-generated by scripts/build.py - do not edit manually
const files = [
  "aubergine-chermoula.md",
  "chicken-with-fennel-beans-lemon.md",
  "chocolate-almond-torte.md",
  "chocolate-and-beetroot-cake.md",
  "fasolakia.md",
  "italian-potato-salad.md",
  "lentejas-a-la-margarita.md",
  "moussaka.md",
  "pavlova.md",
  "roast-beef.md",
  "roast-potatoes.md",
  "spicy-roast-lamb.md",
  "tuna-and-white-bean-salad.md"
];
