#!/usr/bin/env python3
import json
import os

def build_recipe_manifest():
    repo_dir = os.path.dirname(os.path.abspath(__file__))
    recipes_dir = os.path.join(repo_dir, "recipes")
    files = sorted([
        f for f in os.listdir(recipes_dir)
        if f.endswith(".md") and not f.startswith("_") and f != "recipe-template.md"
    ])
    
    output_file = os.path.join(repo_dir, "recipes.js")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build.py - do not edit manually\n")
        f.write("const files = ")
        f.write(json.dumps(files, indent=2))
        f.write(";\n")
    
    print(f"Generated recipes.js with {len(files)} recipes.")

if __name__ == "__main__":
    build_recipe_manifest()
