#!/usr/bin/env python3
import json
import os

def extract_recipe_title(filepath: str, default_title: str) -> str:
    """Extract the first '# Title' line from a recipe markdown file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            for line in f:
                stripped = line.strip()
                if stripped.startswith("# "):
                    return stripped[2:].strip()
    except Exception as e:
        print(f"Warning: Could not read {filepath}: {e}")
    return default_title

def build_recipe_manifest():
    repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    recipes_dir = os.path.join(repo_dir, "recipes")
    raw_files = sorted([
        f for f in os.listdir(recipes_dir)
        if f.endswith(".md") and not f.startswith("_")
    ])

    images_dir = os.path.join(repo_dir, "images")
    recipes = []
    for filename in raw_files:
        filepath = os.path.join(recipes_dir, filename)
        slug = filename[:-3]
        fallback_title = slug.replace("-", " ").title()
        title = extract_recipe_title(filepath, fallback_title)
        has_image = os.path.isfile(os.path.join(images_dir, f"{slug}.jpg"))
        recipes.append({
            "title": title,
            "slug": slug,
            "filename": filename,
            "has_image": has_image
        })

    # Sort alphabetically by title (case-insensitive)
    recipes.sort(key=lambda r: r["title"].lower())

    output_file = os.path.join(repo_dir, "js", "recipes.js")
    with open(output_file, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by scripts/build.py - do not edit manually\n")
        f.write("const recipes = ")
        f.write(json.dumps(recipes, indent=2))
        f.write(";\n\n")
        f.write("// Backward-compatibility for any scripts expecting array of filenames\n")
        f.write("const files = recipes.map(r => r.filename);\n")

    print(f"Generated js/recipes.js with {len(recipes)} recipes.")

if __name__ == "__main__":
    build_recipe_manifest()
